refactor toxenvs, use OpenAstronomy workflows, and move MacOS jobs to schedule
spacetelescope/roman_datamodels pull request #114
Opened 2022-12-12 19:48 UTC by zacharyburnett

This PR abstracts CI workflows to the OpenAstronomy workflows; this should reduce maintenance for updating and maintaining actions. Additionally, these changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/16024299/225091302-038f2234-74df-4d3f-b9f4-722f40246f80.png">

2023-01-11 18:34 UTC, WilliamJamieson commented
@zacharyburnett what is the status of this PR?

2023-01-11 19:40 UTC, zacharyburnett commented
> @zacharyburnett what is the status of this PR?

There's an issue with `test-pyargs` that I couldn't pin down, but other than that it looks ready.

2023-03-21 01:47 UTC, WilliamJamieson commented
Line 7 of the `ci.yml` workflow should either be removed, or be replaced with a regex like `"*.*.x"` so that it does not match on every single branch (the suggested regex would only match on the release branch pattern).

2023-03-22 14:58 UTC, WilliamJamieson requested changes

2023-03-22 14:58 UTC, WilliamJamieson commented on .github/workflows/ci.yml
> +          python-version: 3.10
Same basic comment as https://github.com/spacetelescope/stcal/pull/153#discussion_r1144948878

2023-03-22 17:22 UTC, WilliamJamieson approved these changes

2023-03-22 17:22 UTC, WilliamJamieson commented on pyproject.toml
> +    'numpy >=1.20',
This probably deserves a changelog entry.

2023-03-22 17:41 UTC, merged