drop support for Python 3.8
spacetelescope/roman_datamodels pull request #155
Opened 2023-04-14 17:00 UTC by zacharyburnett

Numpy is imminently dropping support for Python 3.8

2023-04-14 17:14 UTC, WilliamJamieson requested changes

2023-04-14 17:14 UTC, WilliamJamieson commented on .readthedocs.yaml
> +
The RTD configuration should be redone to use mamba, see https://github.com/astropy/astropy/blob/main/.readthedocs.yaml for an example

2023-04-14 17:15 UTC, zacharyburnett commented on .readthedocs.yaml
> +    python: "3.11"
```suggestion
    python: "mambaforge-4.10"
```

2023-04-17 12:32 UTC, zacharyburnett commented
It looks like the docs build is failing with the following:
https://readthedocs.org/projects/roman-datamodels/builds/20119428/
```
/home/docs/checkouts/readthedocs.org/user_builds/roman-datamodels/checkouts/155/docs/roman_datamodels/datamodels/developer_api.rst:113: WARNING: autosummary: stub file not found 'roman_datamodels.stuserdict.Any'. Check your autosummary_generate setting.
```

2023-04-18 15:32 UTC, nden commented
@zacharyburnett I wonder if this helps
https://stackoverflow.com/questions/47344477/how-to-exclude-imports-from-automodapi-output/68984608#68984608

2023-04-24 15:37 UTC, nden commented
@zacharyburnett This needs a change log entry

2023-05-10 17:57 UTC, WilliamJamieson requested changes
- https://github.com/spacetelescope/roman_datamodels/blob/ae1caffaa0cccebdbfa2ac41907c8e6717d52ad2/src/roman_datamodels/stnode.py#L27-L30 should be fixed as this is for python 3.8 support
- Fix merge conflicts.

2023-05-12 02:24 UTC, PaulHuwe approved these changes
LGTM

2023-05-15 12:11 UTC, nden commented
@zacharyburnett There's now an ImportError. Once this is fixed we can merge.

> "datamodels-1.0.yaml"
> E   NameError: name 'importlib_resources' is not defined

2023-05-15 12:33 UTC, nden approved these changes

2023-05-15 12:34 UTC, nden commented
The change request was addressed, merging.

2023-05-15 12:34 UTC, merged