test against pre-built binaries of `astropy` and `numpy`
spacetelescope/roman_datamodels pull request #171
Opened 2023-05-09 14:04 UTC by zacharyburnett

Resolves [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)

This PR runs `devdeps` tests against the latest `pre` wheels of `astropy` and `numpy`

**Checklist**
- [ ] ~Added entry in `CHANGES.rst` under the corresponding subsection~
- [ ] updated relevant tests
- [ ] ~updated relevant documentation~
- [ ] ~Passed romancal regression testing on Jenkins / PLWishMaster. Link: https://plwishmaster.stsci.edu:8081/job/RT/job/romancal/XXX/~

2023-05-09 18:23 UTC, ddavis-stsci approved these changes
Since this does pass the regression tests,
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/171/

2023-05-09 20:19 UTC, WilliamJamieson requested changes

2023-05-09 20:19 UTC, WilliamJamieson commented on tox.ini
> +    devdeps: numpy>=0.0.dev0
This is doing nothing, `pip` will just fall back on the latest version in the PyPi index (i.e. the latest release in it). If you want to use the "pre-built" presumably nightly binaries, you will have to specify extra indexes for pip to use.

https://github.com/spacetelescope/jdaviz/blob/0194237dcc45a5cda6d837d39b6527edada71d47/tox.ini#L72
indicates a possibility for astropy, though it should build just fine off main

https://github.com/astropy/astropy/blob/337798f36c9aa2ae98190c5819bde758d3aa5a40/tox.ini#L27 is how you specify the extra index for numpy nightly wheels.

2023-05-10 14:40 UTC, zacharyburnett commented
GitHub Actions are currently degraded; running `tox -e test-devdeps-xdist` locally results in the following `pip freeze`: 
```
asdf==2.15.0
asdf-astropy==0.4.0
asdf-coordinates-schemas==0.2.0
asdf-standard==1.0.3
asdf-transform-schemas==0.3.0
asdf-unit-schemas==0.1.0
asdf-wcs-schemas==0.1.1
astropy @ git+https://github.com/astropy/astropy@f2fbb112983e953fb772c5ac81ec50dfa34bcc19
attrs==23.1.0
execnet==1.9.0
gwcs==0.18.3
importlib-metadata==6.6.0
iniconfig==2.0.0
jmespath==1.0.1
jsonschema==4.17.3
numpy==1.25.0.dev0+1357.ga2d21d8ac
packaging==23.1
pluggy==1.0.0
psutil==5.9.5
pyerfa==2.0.0.3
pyrsistent==0.19.3
pytest==7.3.1
pytest-doctestplus==0.12.1
pytest-xdist==3.2.1
PyYAML==6.0
rad==0.14.2
roman-datamodels @ file:///Users/zburnett/projects/roman_datamodels/.tox/.tmp/package/2/roman_datamodels-0.14.3.dev25%2Bg6aeacc6.tar.gz#sha256=856cc4dc39f5d66317fca4e7f153a8f56972b3575c0fe8227cb55b90c408cada
scipy==1.10.1
semantic-version==2.10.0
zipp==3.15.0
```

2023-05-15 12:51 UTC, merged