Changes to support new rad tags
spacetelescope/roman_datamodels pull request #86
Opened 2022-07-26 18:33 UTC by WilliamJamieson

These are the changes to the datamodels in order to support spacetelescope/rad#153.

The reason for these changes is to enable recovery of the information stored in the schemas for `archive_catalog` and `sdf` from an open data model. If this data is located as a primary key of a tagged schema or under the properties of that schema, then ASDF can easily retrieve this data, to see this note that now more things in the `model.info()` have title comments.

2022-07-26 20:09 UTC, PaulHuwe requested changes

2022-07-26 20:09 UTC, PaulHuwe commented on src/roman_datamodels/stnode.py
> +                raise jsonschema.ValidationError("origin must be 'ROMAN'")
```suggestion
                raise jsonschema.ValidationError("telescope must be 'ROMAN'")
```

2022-07-26 20:09 UTC, PaulHuwe commented on src/roman_datamodels/stnode.py
> +                raise jsonschema.ValidationError("origin must be 'ROMAN'")
```suggestion
                raise jsonschema.ValidationError("telescope must be 'ROMAN'")
```

2022-07-26 20:12 UTC, WilliamJamieson commented on src/roman_datamodels/stnode.py
> +                value[sub_key] = self._convert_to_scalar(sub_key, sub_value)
It is recursive because every nested (dictionary) level is recursively added as a specific subclass of `DNode`.

2022-07-26 20:33 UTC, PaulHuwe approved these changes
LGTM

2022-07-26 21:30 UTC, perrygreenfield approved these changes
I like it.

2022-07-27 00:09 UTC, WilliamJamieson commented
CI will pass now that PR spacetelescope/rad#15 has been merged. It just needs the CI restarted.

2022-07-27 01:47 UTC, merged